// Code generated by wincallback.go using 'go generate'. DO NOT EDIT.

// External code calls into callbackasm at an offset corresponding
// to the callback index. Callbackasm is a table of MOV and B instructions.
// The MOV instruction loads R16 with the callback index, and the
// B instruction branches to callbackasm1.
// callbackasm1 takes the callback index from R16 and
// indexes into an array that stores information about each callback.
// It then calls the Go implementation for that callback.
#include "textflag.h"

TEXT runtime·callbackasm(SB),NOSPLIT|NOFRAME,$0
	MOVD	$0, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1, R16
	B	runtime·callbackasm1(SB)
	MOVD	$2, R16
	B	runtime·callbackasm1(SB)
	MOVD	$3, R16
	B	runtime·callbackasm1(SB)
	MOVD	$4, R16
	B	runtime·callbackasm1(SB)
	MOVD	$5, R16
	B	runtime·callbackasm1(SB)
	MOVD	$6, R16
	B	runtime·callbackasm1(SB)
	MOVD	$7, R16
	B	runtime·callbackasm1(SB)
	MOVD	$8, R16
	B	runtime·callbackasm1(SB)
	MOVD	$9, R16
	B	runtime·callbackasm1(SB)
	MOVD	$10, R16
	B	runtime·callbackasm1(SB)
	MOVD	$11, R16
	B	runtime·callbackasm1(SB)
	MOVD	$12, R16
	B	runtime·callbackasm1(SB)
	MOVD	$13, R16
	B	runtime·callbackasm1(SB)
	MOVD	$14, R16
	B	runtime·callbackasm1(SB)
	MOVD	$15, R16
	B	runtime·callbackasm1(SB)
	MOVD	$16, R16
	B	runtime·callbackasm1(SB)
	MOVD	$17, R16
	B	runtime·callbackasm1(SB)
	MOVD	$18, R16
	B	runtime·callbackasm1(SB)
	MOVD	$19, R16
	B	runtime·callbackasm1(SB)
	MOVD	$20, R16
	B	runtime·callbackasm1(SB)
	MOVD	$21, R16
	B	runtime·callbackasm1(SB)
	MOVD	$22, R16
	B	runtime·callbackasm1(SB)
	MOVD	$23, R16
	B	runtime·callbackasm1(SB)
	MOVD	$24, R16
	B	runtime·callbackasm1(SB)
	MOVD	$25, R16
	B	runtime·callbackasm1(SB)
	MOVD	$26, R16
	B	runtime·callbackasm1(SB)
	MOVD	$27, R16
	B	runtime·callbackasm1(SB)
	MOVD	$28, R16
	B	runtime·callbackasm1(SB)
	MOVD	$29, R16
	B	runtime·callbackasm1(SB)
	MOVD	$30, R16
	B	runtime·callbackasm1(SB)
	MOVD	$31, R16
	B	runtime·callbackasm1(SB)
	MOVD	$32, R16
	B	runtime·callbackasm1(SB)
	MOVD	$33, R16
	B	runtime·callbackasm1(SB)
	MOVD	$34, R16
	B	runtime·callbackasm1(SB)
	MOVD	$35, R16
	B	runtime·callbackasm1(SB)
	MOVD	$36, R16
	B	runtime·callbackasm1(SB)
	MOVD	$37, R16
	B	runtime·callbackasm1(SB)
	MOVD	$38, R16
	B	runtime·callbackasm1(SB)
	MOVD	$39, R16
	B	runtime·callbackasm1(SB)
	MOVD	$40, R16
	B	runtime·callbackasm1(SB)
	MOVD	$41, R16
	B	runtime·callbackasm1(SB)
	MOVD	$42, R16
	B	runtime·callbackasm1(SB)
	MOVD	$43, R16
	B	runtime·callbackasm1(SB)
	MOVD	$44, R16
	B	runtime·callbackasm1(SB)
	MOVD	$45, R16
	B	runtime·callbackasm1(SB)
	MOVD	$46, R16
	B	runtime·callbackasm1(SB)
	MOVD	$47, R16
	B	runtime·callbackasm1(SB)
	MOVD	$48, R16
	B	runtime·callbackasm1(SB)
	MOVD	$49, R16
	B	runtime·callbackasm1(SB)
	MOVD	$50, R16
	B	runtime·callbackasm1(SB)
	MOVD	$51, R16
	B	runtime·callbackasm1(SB)
	MOVD	$52, R16
	B	runtime·callbackasm1(SB)
	MOVD	$53, R16
	B	runtime·callbackasm1(SB)
	MOVD	$54, R16
	B	runtime·callbackasm1(SB)
	MOVD	$55, R16
	B	runtime·callbackasm1(SB)
	MOVD	$56, R16
	B	runtime·callbackasm1(SB)
	MOVD	$57, R16
	B	runtime·callbackasm1(SB)
	MOVD	$58, R16
	B	runtime·callbackasm1(SB)
	MOVD	$59, R16
	B	runtime·callbackasm1(SB)
	MOVD	$60, R16
	B	runtime·callbackasm1(SB)
	MOVD	$61, R16
	B	runtime·callbackasm1(SB)
	MOVD	$62, R16
	B	runtime·callbackasm1(SB)
	MOVD	$63, R16
	B	runtime·callbackasm1(SB)
	MOVD	$64, R16
	B	runtime·callbackasm1(SB)
	MOVD	$65, R16
	B	runtime·callbackasm1(SB)
	MOVD	$66, R16
	B	runtime·callbackasm1(SB)
	MOVD	$67, R16
	B	runtime·callbackasm1(SB)
	MOVD	$68, R16
	B	runtime·callbackasm1(SB)
	MOVD	$69, R16
	B	runtime·callbackasm1(SB)
	MOVD	$70, R16
	B	runtime·callbackasm1(SB)
	MOVD	$71, R16
	B	runtime·callbackasm1(SB)
	MOVD	$72, R16
	B	runtime·callbackasm1(SB)
	MOVD	$73, R16
	B	runtime·callbackasm1(SB)
	MOVD	$74, R16
	B	runtime·callbackasm1(SB)
	MOVD	$75, R16
	B	runtime·callbackasm1(SB)
	MOVD	$76, R16
	B	runtime·callbackasm1(SB)
	MOVD	$77, R16
	B	runtime·callbackasm1(SB)
	MOVD	$78, R16
	B	runtime·callbackasm1(SB)
	MOVD	$79, R16
	B	runtime·callbackasm1(SB)
	MOVD	$80, R16
	B	runtime·callbackasm1(SB)
	MOVD	$81, R16
	B	runtime·callbackasm1(SB)
	MOVD	$82, R16
	B	runtime·callbackasm1(SB)
	MOVD	$83, R16
	B	runtime·callbackasm1(SB)
	MOVD	$84, R16
	B	runtime·callbackasm1(SB)
	MOVD	$85, R16
	B	runtime·callbackasm1(SB)
	MOVD	$86, R16
	B	runtime·callbackasm1(SB)
	MOVD	$87, R16
	B	runtime·callbackasm1(SB)
	MOVD	$88, R16
	B	runtime·callbackasm1(SB)
	MOVD	$89, R16
	B	runtime·callbackasm1(SB)
	MOVD	$90, R16
	B	runtime·callbackasm1(SB)
	MOVD	$91, R16
	B	runtime·callbackasm1(SB)
	MOVD	$92, R16
	B	runtime·callbackasm1(SB)
	MOVD	$93, R16
	B	runtime·callbackasm1(SB)
	MOVD	$94, R16
	B	runtime·callbackasm1(SB)
	MOVD	$95, R16
	B	runtime·callbackasm1(SB)
	MOVD	$96, R16
	B	runtime·callbackasm1(SB)
	MOVD	$97, R16
	B	runtime·callbackasm1(SB)
	MOVD	$98, R16
	B	runtime·callbackasm1(SB)
	MOVD	$99, R16
	B	runtime·callbackasm1(SB)
	MOVD	$100, R16
	B	runtime·callbackasm1(SB)
	MOVD	$101, R16
	B	runtime·callbackasm1(SB)
	MOVD	$102, R16
	B	runtime·callbackasm1(SB)
	MOVD	$103, R16
	B	runtime·callbackasm1(SB)
	MOVD	$104, R16
	B	runtime·callbackasm1(SB)
	MOVD	$105, R16
	B	runtime·callbackasm1(SB)
	MOVD	$106, R16
	B	runtime·callbackasm1(SB)
	MOVD	$107, R16
	B	runtime·callbackasm1(SB)
	MOVD	$108, R16
	B	runtime·callbackasm1(SB)
	MOVD	$109, R16
	B	runtime·callbackasm1(SB)
	MOVD	$110, R16
	B	runtime·callbackasm1(SB)
	MOVD	$111, R16
	B	runtime·callbackasm1(SB)
	MOVD	$112, R16
	B	runtime·callbackasm1(SB)
	MOVD	$113, R16
	B	runtime·callbackasm1(SB)
	MOVD	$114, R16
	B	runtime·callbackasm1(SB)
	MOVD	$115, R16
	B	runtime·callbackasm1(SB)
	MOVD	$116, R16
	B	runtime·callbackasm1(SB)
	MOVD	$117, R16
	B	runtime·callbackasm1(SB)
	MOVD	$118, R16
	B	runtime·callbackasm1(SB)
	MOVD	$119, R16
	B	runtime·callbackasm1(SB)
	MOVD	$120, R16
	B	runtime·callbackasm1(SB)
	MOVD	$121, R16
	B	runtime·callbackasm1(SB)
	MOVD	$122, R16
	B	runtime·callbackasm1(SB)
	MOVD	$123, R16
	B	runtime·callbackasm1(SB)
	MOVD	$124, R16
	B	runtime·callbackasm1(SB)
	MOVD	$125, R16
	B	runtime·callbackasm1(SB)
	MOVD	$126, R16
	B	runtime·callbackasm1(SB)
	MOVD	$127, R16
	B	runtime·callbackasm1(SB)
	MOVD	$128, R16
	B	runtime·callbackasm1(SB)
	MOVD	$129, R16
	B	runtime·callbackasm1(SB)
	MOVD	$130, R16
	B	runtime·callbackasm1(SB)
	MOVD	$131, R16
	B	runtime·callbackasm1(SB)
	MOVD	$132, R16
	B	runtime·callbackasm1(SB)
	MOVD	$133, R16
	B	runtime·callbackasm1(SB)
	MOVD	$134, R16
	B	runtime·callbackasm1(SB)
	MOVD	$135, R16
	B	runtime·callbackasm1(SB)
	MOVD	$136, R16
	B	runtime·callbackasm1(SB)
	MOVD	$137, R16
	B	runtime·callbackasm1(SB)
	MOVD	$138, R16
	B	runtime·callbackasm1(SB)
	MOVD	$139, R16
	B	runtime·callbackasm1(SB)
	MOVD	$140, R16
	B	runtime·callbackasm1(SB)
	MOVD	$141, R16
	B	runtime·callbackasm1(SB)
	MOVD	$142, R16
	B	runtime·callbackasm1(SB)
	MOVD	$143, R16
	B	runtime·callbackasm1(SB)
	MOVD	$144, R16
	B	runtime·callbackasm1(SB)
	MOVD	$145, R16
	B	runtime·callbackasm1(SB)
	MOVD	$146, R16
	B	runtime·callbackasm1(SB)
	MOVD	$147, R16
	B	runtime·callbackasm1(SB)
	MOVD	$148, R16
	B	runtime·callbackasm1(SB)
	MOVD	$149, R16
	B	runtime·callbackasm1(SB)
	MOVD	$150, R16
	B	runtime·callbackasm1(SB)
	MOVD	$151, R16
	B	runtime·callbackasm1(SB)
	MOVD	$152, R16
	B	runtime·callbackasm1(SB)
	MOVD	$153, R16
	B	runtime·callbackasm1(SB)
	MOVD	$154, R16
	B	runtime·callbackasm1(SB)
	MOVD	$155, R16
	B	runtime·callbackasm1(SB)
	MOVD	$156, R16
	B	runtime·callbackasm1(SB)
	MOVD	$157, R16
	B	runtime·callbackasm1(SB)
	MOVD	$158, R16
	B	runtime·callbackasm1(SB)
	MOVD	$159, R16
	B	runtime·callbackasm1(SB)
	MOVD	$160, R16
	B	runtime·callbackasm1(SB)
	MOVD	$161, R16
	B	runtime·callbackasm1(SB)
	MOVD	$162, R16
	B	runtime·callbackasm1(SB)
	MOVD	$163, R16
	B	runtime·callbackasm1(SB)
	MOVD	$164, R16
	B	runtime·callbackasm1(SB)
	MOVD	$165, R16
	B	runtime·callbackasm1(SB)
	MOVD	$166, R16
	B	runtime·callbackasm1(SB)
	MOVD	$167, R16
	B	runtime·callbackasm1(SB)
	MOVD	$168, R16
	B	runtime·callbackasm1(SB)
	MOVD	$169, R16
	B	runtime·callbackasm1(SB)
	MOVD	$170, R16
	B	runtime·callbackasm1(SB)
	MOVD	$171, R16
	B	runtime·callbackasm1(SB)
	MOVD	$172, R16
	B	runtime·callbackasm1(SB)
	MOVD	$173, R16
	B	runtime·callbackasm1(SB)
	MOVD	$174, R16
	B	runtime·callbackasm1(SB)
	MOVD	$175, R16
	B	runtime·callbackasm1(SB)
	MOVD	$176, R16
	B	runtime·callbackasm1(SB)
	MOVD	$177, R16
	B	runtime·callbackasm1(SB)
	MOVD	$178, R16
	B	runtime·callbackasm1(SB)
	MOVD	$179, R16
	B	runtime·callbackasm1(SB)
	MOVD	$180, R16
	B	runtime·callbackasm1(SB)
	MOVD	$181, R16
	B	runtime·callbackasm1(SB)
	MOVD	$182, R16
	B	runtime·callbackasm1(SB)
	MOVD	$183, R16
	B	runtime·callbackasm1(SB)
	MOVD	$184, R16
	B	runtime·callbackasm1(SB)
	MOVD	$185, R16
	B	runtime·callbackasm1(SB)
	MOVD	$186, R16
	B	runtime·callbackasm1(SB)
	MOVD	$187, R16
	B	runtime·callbackasm1(SB)
	MOVD	$188, R16
	B	runtime·callbackasm1(SB)
	MOVD	$189, R16
	B	runtime·callbackasm1(SB)
	MOVD	$190, R16
	B	runtime·callbackasm1(SB)
	MOVD	$191, R16
	B	runtime·callbackasm1(SB)
	MOVD	$192, R16
	B	runtime·callbackasm1(SB)
	MOVD	$193, R16
	B	runtime·callbackasm1(SB)
	MOVD	$194, R16
	B	runtime·callbackasm1(SB)
	MOVD	$195, R16
	B	runtime·callbackasm1(SB)
	MOVD	$196, R16
	B	runtime·callbackasm1(SB)
	MOVD	$197, R16
	B	runtime·callbackasm1(SB)
	MOVD	$198, R16
	B	runtime·callbackasm1(SB)
	MOVD	$199, R16
	B	runtime·callbackasm1(SB)
	MOVD	$200, R16
	B	runtime·callbackasm1(SB)
	MOVD	$201, R16
	B	runtime·callbackasm1(SB)
	MOVD	$202, R16
	B	runtime·callbackasm1(SB)
	MOVD	$203, R16
	B	runtime·callbackasm1(SB)
	MOVD	$204, R16
	B	runtime·callbackasm1(SB)
	MOVD	$205, R16
	B	runtime·callbackasm1(SB)
	MOVD	$206, R16
	B	runtime·callbackasm1(SB)
	MOVD	$207, R16
	B	runtime·callbackasm1(SB)
	MOVD	$208, R16
	B	runtime·callbackasm1(SB)
	MOVD	$209, R16
	B	runtime·callbackasm1(SB)
	MOVD	$210, R16
	B	runtime·callbackasm1(SB)
	MOVD	$211, R16
	B	runtime·callbackasm1(SB)
	MOVD	$212, R16
	B	runtime·callbackasm1(SB)
	MOVD	$213, R16
	B	runtime·callbackasm1(SB)
	MOVD	$214, R16
	B	runtime·callbackasm1(SB)
	MOVD	$215, R16
	B	runtime·callbackasm1(SB)
	MOVD	$216, R16
	B	runtime·callbackasm1(SB)
	MOVD	$217, R16
	B	runtime·callbackasm1(SB)
	MOVD	$218, R16
	B	runtime·callbackasm1(SB)
	MOVD	$219, R16
	B	runtime·callbackasm1(SB)
	MOVD	$220, R16
	B	runtime·callbackasm1(SB)
	MOVD	$221, R16
	B	runtime·callbackasm1(SB)
	MOVD	$222, R16
	B	runtime·callbackasm1(SB)
	MOVD	$223, R16
	B	runtime·callbackasm1(SB)
	MOVD	$224, R16
	B	runtime·callbackasm1(SB)
	MOVD	$225, R16
	B	runtime·callbackasm1(SB)
	MOVD	$226, R16
	B	runtime·callbackasm1(SB)
	MOVD	$227, R16
	B	runtime·callbackasm1(SB)
	MOVD	$228, R16
	B	runtime·callbackasm1(SB)
	MOVD	$229, R16
	B	runtime·callbackasm1(SB)
	MOVD	$230, R16
	B	runtime·callbackasm1(SB)
	MOVD	$231, R16
	B	runtime·callbackasm1(SB)
	MOVD	$232, R16
	B	runtime·callbackasm1(SB)
	MOVD	$233, R16
	B	runtime·callbackasm1(SB)
	MOVD	$234, R16
	B	runtime·callbackasm1(SB)
	MOVD	$235, R16
	B	runtime·callbackasm1(SB)
	MOVD	$236, R16
	B	runtime·callbackasm1(SB)
	MOVD	$237, R16
	B	runtime·callbackasm1(SB)
	MOVD	$238, R16
	B	runtime·callbackasm1(SB)
	MOVD	$239, R16
	B	runtime·callbackasm1(SB)
	MOVD	$240, R16
	B	runtime·callbackasm1(SB)
	MOVD	$241, R16
	B	runtime·callbackasm1(SB)
	MOVD	$242, R16
	B	runtime·callbackasm1(SB)
	MOVD	$243, R16
	B	runtime·callbackasm1(SB)
	MOVD	$244, R16
	B	runtime·callbackasm1(SB)
	MOVD	$245, R16
	B	runtime·callbackasm1(SB)
	MOVD	$246, R16
	B	runtime·callbackasm1(SB)
	MOVD	$247, R16
	B	runtime·callbackasm1(SB)
	MOVD	$248, R16
	B	runtime·callbackasm1(SB)
	MOVD	$249, R16
	B	runtime·callbackasm1(SB)
	MOVD	$250, R16
	B	runtime·callbackasm1(SB)
	MOVD	$251, R16
	B	runtime·callbackasm1(SB)
	MOVD	$252, R16
	B	runtime·callbackasm1(SB)
	MOVD	$253, R16
	B	runtime·callbackasm1(SB)
	MOVD	$254, R16
	B	runtime·callbackasm1(SB)
	MOVD	$255, R16
	B	runtime·callbackasm1(SB)
	MOVD	$256, R16
	B	runtime·callbackasm1(SB)
	MOVD	$257, R16
	B	runtime·callbackasm1(SB)
	MOVD	$258, R16
	B	runtime·callbackasm1(SB)
	MOVD	$259, R16
	B	runtime·callbackasm1(SB)
	MOVD	$260, R16
	B	runtime·callbackasm1(SB)
	MOVD	$261, R16
	B	runtime·callbackasm1(SB)
	MOVD	$262, R16
	B	runtime·callbackasm1(SB)
	MOVD	$263, R16
	B	runtime·callbackasm1(SB)
	MOVD	$264, R16
	B	runtime·callbackasm1(SB)
	MOVD	$265, R16
	B	runtime·callbackasm1(SB)
	MOVD	$266, R16
	B	runtime·callbackasm1(SB)
	MOVD	$267, R16
	B	runtime·callbackasm1(SB)
	MOVD	$268, R16
	B	runtime·callbackasm1(SB)
	MOVD	$269, R16
	B	runtime·callbackasm1(SB)
	MOVD	$270, R16
	B	runtime·callbackasm1(SB)
	MOVD	$271, R16
	B	runtime·callbackasm1(SB)
	MOVD	$272, R16
	B	runtime·callbackasm1(SB)
	MOVD	$273, R16
	B	runtime·callbackasm1(SB)
	MOVD	$274, R16
	B	runtime·callbackasm1(SB)
	MOVD	$275, R16
	B	runtime·callbackasm1(SB)
	MOVD	$276, R16
	B	runtime·callbackasm1(SB)
	MOVD	$277, R16
	B	runtime·callbackasm1(SB)
	MOVD	$278, R16
	B	runtime·callbackasm1(SB)
	MOVD	$279, R16
	B	runtime·callbackasm1(SB)
	MOVD	$280, R16
	B	runtime·callbackasm1(SB)
	MOVD	$281, R16
	B	runtime·callbackasm1(SB)
	MOVD	$282, R16
	B	runtime·callbackasm1(SB)
	MOVD	$283, R16
	B	runtime·callbackasm1(SB)
	MOVD	$284, R16
	B	runtime·callbackasm1(SB)
	MOVD	$285, R16
	B	runtime·callbackasm1(SB)
	MOVD	$286, R16
	B	runtime·callbackasm1(SB)
	MOVD	$287, R16
	B	runtime·callbackasm1(SB)
	MOVD	$288, R16
	B	runtime·callbackasm1(SB)
	MOVD	$289, R16
	B	runtime·callbackasm1(SB)
	MOVD	$290, R16
	B	runtime·callbackasm1(SB)
	MOVD	$291, R16
	B	runtime·callbackasm1(SB)
	MOVD	$292, R16
	B	runtime·callbackasm1(SB)
	MOVD	$293, R16
	B	runtime·callbackasm1(SB)
	MOVD	$294, R16
	B	runtime·callbackasm1(SB)
	MOVD	$295, R16
	B	runtime·callbackasm1(SB)
	MOVD	$296, R16
	B	runtime·callbackasm1(SB)
	MOVD	$297, R16
	B	runtime·callbackasm1(SB)
	MOVD	$298, R16
	B	runtime·callbackasm1(SB)
	MOVD	$299, R16
	B	runtime·callbackasm1(SB)
	MOVD	$300, R16
	B	runtime·callbackasm1(SB)
	MOVD	$301, R16
	B	runtime·callbackasm1(SB)
	MOVD	$302, R16
	B	runtime·callbackasm1(SB)
	MOVD	$303, R16
	B	runtime·callbackasm1(SB)
	MOVD	$304, R16
	B	runtime·callbackasm1(SB)
	MOVD	$305, R16
	B	runtime·callbackasm1(SB)
	MOVD	$306, R16
	B	runtime·callbackasm1(SB)
	MOVD	$307, R16
	B	runtime·callbackasm1(SB)
	MOVD	$308, R16
	B	runtime·callbackasm1(SB)
	MOVD	$309, R16
	B	runtime·callbackasm1(SB)
	MOVD	$310, R16
	B	runtime·callbackasm1(SB)
	MOVD	$311, R16
	B	runtime·callbackasm1(SB)
	MOVD	$312, R16
	B	runtime·callbackasm1(SB)
	MOVD	$313, R16
	B	runtime·callbackasm1(SB)
	MOVD	$314, R16
	B	runtime·callbackasm1(SB)
	MOVD	$315, R16
	B	runtime·callbackasm1(SB)
	MOVD	$316, R16
	B	runtime·callbackasm1(SB)
	MOVD	$317, R16
	B	runtime·callbackasm1(SB)
	MOVD	$318, R16
	B	runtime·callbackasm1(SB)
	MOVD	$319, R16
	B	runtime·callbackasm1(SB)
	MOVD	$320, R16
	B	runtime·callbackasm1(SB)
	MOVD	$321, R16
	B	runtime·callbackasm1(SB)
	MOVD	$322, R16
	B	runtime·callbackasm1(SB)
	MOVD	$323, R16
	B	runtime·callbackasm1(SB)
	MOVD	$324, R16
	B	runtime·callbackasm1(SB)
	MOVD	$325, R16
	B	runtime·callbackasm1(SB)
	MOVD	$326, R16
	B	runtime·callbackasm1(SB)
	MOVD	$327, R16
	B	runtime·callbackasm1(SB)
	MOVD	$328, R16
	B	runtime·callbackasm1(SB)
	MOVD	$329, R16
	B	runtime·callbackasm1(SB)
	MOVD	$330, R16
	B	runtime·callbackasm1(SB)
	MOVD	$331, R16
	B	runtime·callbackasm1(SB)
	MOVD	$332, R16
	B	runtime·callbackasm1(SB)
	MOVD	$333, R16
	B	runtime·callbackasm1(SB)
	MOVD	$334, R16
	B	runtime·callbackasm1(SB)
	MOVD	$335, R16
	B	runtime·callbackasm1(SB)
	MOVD	$336, R16
	B	runtime·callbackasm1(SB)
	MOVD	$337, R16
	B	runtime·callbackasm1(SB)
	MOVD	$338, R16
	B	runtime·callbackasm1(SB)
	MOVD	$339, R16
	B	runtime·callbackasm1(SB)
	MOVD	$340, R16
	B	runtime·callbackasm1(SB)
	MOVD	$341, R16
	B	runtime·callbackasm1(SB)
	MOVD	$342, R16
	B	runtime·callbackasm1(SB)
	MOVD	$343, R16
	B	runtime·callbackasm1(SB)
	MOVD	$344, R16
	B	runtime·callbackasm1(SB)
	MOVD	$345, R16
	B	runtime·callbackasm1(SB)
	MOVD	$346, R16
	B	runtime·callbackasm1(SB)
	MOVD	$347, R16
	B	runtime·callbackasm1(SB)
	MOVD	$348, R16
	B	runtime·callbackasm1(SB)
	MOVD	$349, R16
	B	runtime·callbackasm1(SB)
	MOVD	$350, R16
	B	runtime·callbackasm1(SB)
	MOVD	$351, R16
	B	runtime·callbackasm1(SB)
	MOVD	$352, R16
	B	runtime·callbackasm1(SB)
	MOVD	$353, R16
	B	runtime·callbackasm1(SB)
	MOVD	$354, R16
	B	runtime·callbackasm1(SB)
	MOVD	$355, R16
	B	runtime·callbackasm1(SB)
	MOVD	$356, R16
	B	runtime·callbackasm1(SB)
	MOVD	$357, R16
	B	runtime·callbackasm1(SB)
	MOVD	$358, R16
	B	runtime·callbackasm1(SB)
	MOVD	$359, R16
	B	runtime·callbackasm1(SB)
	MOVD	$360, R16
	B	runtime·callbackasm1(SB)
	MOVD	$361, R16
	B	runtime·callbackasm1(SB)
	MOVD	$362, R16
	B	runtime·callbackasm1(SB)
	MOVD	$363, R16
	B	runtime·callbackasm1(SB)
	MOVD	$364, R16
	B	runtime·callbackasm1(SB)
	MOVD	$365, R16
	B	runtime·callbackasm1(SB)
	MOVD	$366, R16
	B	runtime·callbackasm1(SB)
	MOVD	$367, R16
	B	runtime·callbackasm1(SB)
	MOVD	$368, R16
	B	runtime·callbackasm1(SB)
	MOVD	$369, R16
	B	runtime·callbackasm1(SB)
	MOVD	$370, R16
	B	runtime·callbackasm1(SB)
	MOVD	$371, R16
	B	runtime·callbackasm1(SB)
	MOVD	$372, R16
	B	runtime·callbackasm1(SB)
	MOVD	$373, R16
	B	runtime·callbackasm1(SB)
	MOVD	$374, R16
	B	runtime·callbackasm1(SB)
	MOVD	$375, R16
	B	runtime·callbackasm1(SB)
	MOVD	$376, R16
	B	runtime·callbackasm1(SB)
	MOVD	$377, R16
	B	runtime·callbackasm1(SB)
	MOVD	$378, R16
	B	runtime·callbackasm1(SB)
	MOVD	$379, R16
	B	runtime·callbackasm1(SB)
	MOVD	$380, R16
	B	runtime·callbackasm1(SB)
	MOVD	$381, R16
	B	runtime·callbackasm1(SB)
	MOVD	$382, R16
	B	runtime·callbackasm1(SB)
	MOVD	$383, R16
	B	runtime·callbackasm1(SB)
	MOVD	$384, R16
	B	runtime·callbackasm1(SB)
	MOVD	$385, R16
	B	runtime·callbackasm1(SB)
	MOVD	$386, R16
	B	runtime·callbackasm1(SB)
	MOVD	$387, R16
	B	runtime·callbackasm1(SB)
	MOVD	$388, R16
	B	runtime·callbackasm1(SB)
	MOVD	$389, R16
	B	runtime·callbackasm1(SB)
	MOVD	$390, R16
	B	runtime·callbackasm1(SB)
	MOVD	$391, R16
	B	runtime·callbackasm1(SB)
	MOVD	$392, R16
	B	runtime·callbackasm1(SB)
	MOVD	$393, R16
	B	runtime·callbackasm1(SB)
	MOVD	$394, R16
	B	runtime·callbackasm1(SB)
	MOVD	$395, R16
	B	runtime·callbackasm1(SB)
	MOVD	$396, R16
	B	runtime·callbackasm1(SB)
	MOVD	$397, R16
	B	runtime·callbackasm1(SB)
	MOVD	$398, R16
	B	runtime·callbackasm1(SB)
	MOVD	$399, R16
	B	runtime·callbackasm1(SB)
	MOVD	$400, R16
	B	runtime·callbackasm1(SB)
	MOVD	$401, R16
	B	runtime·callbackasm1(SB)
	MOVD	$402, R16
	B	runtime·callbackasm1(SB)
	MOVD	$403, R16
	B	runtime·callbackasm1(SB)
	MOVD	$404, R16
	B	runtime·callbackasm1(SB)
	MOVD	$405, R16
	B	runtime·callbackasm1(SB)
	MOVD	$406, R16
	B	runtime·callbackasm1(SB)
	MOVD	$407, R16
	B	runtime·callbackasm1(SB)
	MOVD	$408, R16
	B	runtime·callbackasm1(SB)
	MOVD	$409, R16
	B	runtime·callbackasm1(SB)
	MOVD	$410, R16
	B	runtime·callbackasm1(SB)
	MOVD	$411, R16
	B	runtime·callbackasm1(SB)
	MOVD	$412, R16
	B	runtime·callbackasm1(SB)
	MOVD	$413, R16
	B	runtime·callbackasm1(SB)
	MOVD	$414, R16
	B	runtime·callbackasm1(SB)
	MOVD	$415, R16
	B	runtime·callbackasm1(SB)
	MOVD	$416, R16
	B	runtime·callbackasm1(SB)
	MOVD	$417, R16
	B	runtime·callbackasm1(SB)
	MOVD	$418, R16
	B	runtime·callbackasm1(SB)
	MOVD	$419, R16
	B	runtime·callbackasm1(SB)
	MOVD	$420, R16
	B	runtime·callbackasm1(SB)
	MOVD	$421, R16
	B	runtime·callbackasm1(SB)
	MOVD	$422, R16
	B	runtime·callbackasm1(SB)
	MOVD	$423, R16
	B	runtime·callbackasm1(SB)
	MOVD	$424, R16
	B	runtime·callbackasm1(SB)
	MOVD	$425, R16
	B	runtime·callbackasm1(SB)
	MOVD	$426, R16
	B	runtime·callbackasm1(SB)
	MOVD	$427, R16
	B	runtime·callbackasm1(SB)
	MOVD	$428, R16
	B	runtime·callbackasm1(SB)
	MOVD	$429, R16
	B	runtime·callbackasm1(SB)
	MOVD	$430, R16
	B	runtime·callbackasm1(SB)
	MOVD	$431, R16
	B	runtime·callbackasm1(SB)
	MOVD	$432, R16
	B	runtime·callbackasm1(SB)
	MOVD	$433, R16
	B	runtime·callbackasm1(SB)
	MOVD	$434, R16
	B	runtime·callbackasm1(SB)
	MOVD	$435, R16
	B	runtime·callbackasm1(SB)
	MOVD	$436, R16
	B	runtime·callbackasm1(SB)
	MOVD	$437, R16
	B	runtime·callbackasm1(SB)
	MOVD	$438, R16
	B	runtime·callbackasm1(SB)
	MOVD	$439, R16
	B	runtime·callbackasm1(SB)
	MOVD	$440, R16
	B	runtime·callbackasm1(SB)
	MOVD	$441, R16
	B	runtime·callbackasm1(SB)
	MOVD	$442, R16
	B	runtime·callbackasm1(SB)
	MOVD	$443, R16
	B	runtime·callbackasm1(SB)
	MOVD	$444, R16
	B	runtime·callbackasm1(SB)
	MOVD	$445, R16
	B	runtime·callbackasm1(SB)
	MOVD	$446, R16
	B	runtime·callbackasm1(SB)
	MOVD	$447, R16
	B	runtime·callbackasm1(SB)
	MOVD	$448, R16
	B	runtime·callbackasm1(SB)
	MOVD	$449, R16
	B	runtime·callbackasm1(SB)
	MOVD	$450, R16
	B	runtime·callbackasm1(SB)
	MOVD	$451, R16
	B	runtime·callbackasm1(SB)
	MOVD	$452, R16
	B	runtime·callbackasm1(SB)
	MOVD	$453, R16
	B	runtime·callbackasm1(SB)
	MOVD	$454, R16
	B	runtime·callbackasm1(SB)
	MOVD	$455, R16
	B	runtime·callbackasm1(SB)
	MOVD	$456, R16
	B	runtime·callbackasm1(SB)
	MOVD	$457, R16
	B	runtime·callbackasm1(SB)
	MOVD	$458, R16
	B	runtime·callbackasm1(SB)
	MOVD	$459, R16
	B	runtime·callbackasm1(SB)
	MOVD	$460, R16
	B	runtime·callbackasm1(SB)
	MOVD	$461, R16
	B	runtime·callbackasm1(SB)
	MOVD	$462, R16
	B	runtime·callbackasm1(SB)
	MOVD	$463, R16
	B	runtime·callbackasm1(SB)
	MOVD	$464, R16
	B	runtime·callbackasm1(SB)
	MOVD	$465, R16
	B	runtime·callbackasm1(SB)
	MOVD	$466, R16
	B	runtime·callbackasm1(SB)
	MOVD	$467, R16
	B	runtime·callbackasm1(SB)
	MOVD	$468, R16
	B	runtime·callbackasm1(SB)
	MOVD	$469, R16
	B	runtime·callbackasm1(SB)
	MOVD	$470, R16
	B	runtime·callbackasm1(SB)
	MOVD	$471, R16
	B	runtime·callbackasm1(SB)
	MOVD	$472, R16
	B	runtime·callbackasm1(SB)
	MOVD	$473, R16
	B	runtime·callbackasm1(SB)
	MOVD	$474, R16
	B	runtime·callbackasm1(SB)
	MOVD	$475, R16
	B	runtime·callbackasm1(SB)
	MOVD	$476, R16
	B	runtime·callbackasm1(SB)
	MOVD	$477, R16
	B	runtime·callbackasm1(SB)
	MOVD	$478, R16
	B	runtime·callbackasm1(SB)
	MOVD	$479, R16
	B	runtime·callbackasm1(SB)
	MOVD	$480, R16
	B	runtime·callbackasm1(SB)
	MOVD	$481, R16
	B	runtime·callbackasm1(SB)
	MOVD	$482, R16
	B	runtime·callbackasm1(SB)
	MOVD	$483, R16
	B	runtime·callbackasm1(SB)
	MOVD	$484, R16
	B	runtime·callbackasm1(SB)
	MOVD	$485, R16
	B	runtime·callbackasm1(SB)
	MOVD	$486, R16
	B	runtime·callbackasm1(SB)
	MOVD	$487, R16
	B	runtime·callbackasm1(SB)
	MOVD	$488, R16
	B	runtime·callbackasm1(SB)
	MOVD	$489, R16
	B	runtime·callbackasm1(SB)
	MOVD	$490, R16
	B	runtime·callbackasm1(SB)
	MOVD	$491, R16
	B	runtime·callbackasm1(SB)
	MOVD	$492, R16
	B	runtime·callbackasm1(SB)
	MOVD	$493, R16
	B	runtime·callbackasm1(SB)
	MOVD	$494, R16
	B	runtime·callbackasm1(SB)
	MOVD	$495, R16
	B	runtime·callbackasm1(SB)
	MOVD	$496, R16
	B	runtime·callbackasm1(SB)
	MOVD	$497, R16
	B	runtime·callbackasm1(SB)
	MOVD	$498, R16
	B	runtime·callbackasm1(SB)
	MOVD	$499, R16
	B	runtime·callbackasm1(SB)
	MOVD	$500, R16
	B	runtime·callbackasm1(SB)
	MOVD	$501, R16
	B	runtime·callbackasm1(SB)
	MOVD	$502, R16
	B	runtime·callbackasm1(SB)
	MOVD	$503, R16
	B	runtime·callbackasm1(SB)
	MOVD	$504, R16
	B	runtime·callbackasm1(SB)
	MOVD	$505, R16
	B	runtime·callbackasm1(SB)
	MOVD	$506, R16
	B	runtime·callbackasm1(SB)
	MOVD	$507, R16
	B	runtime·callbackasm1(SB)
	MOVD	$508, R16
	B	runtime·callbackasm1(SB)
	MOVD	$509, R16
	B	runtime·callbackasm1(SB)
	MOVD	$510, R16
	B	runtime·callbackasm1(SB)
	MOVD	$511, R16
	B	runtime·callbackasm1(SB)
	MOVD	$512, R16
	B	runtime·callbackasm1(SB)
	MOVD	$513, R16
	B	runtime·callbackasm1(SB)
	MOVD	$514, R16
	B	runtime·callbackasm1(SB)
	MOVD	$515, R16
	B	runtime·callbackasm1(SB)
	MOVD	$516, R16
	B	runtime·callbackasm1(SB)
	MOVD	$517, R16
	B	runtime·callbackasm1(SB)
	MOVD	$518, R16
	B	runtime·callbackasm1(SB)
	MOVD	$519, R16
	B	runtime·callbackasm1(SB)
	MOVD	$520, R16
	B	runtime·callbackasm1(SB)
	MOVD	$521, R16
	B	runtime·callbackasm1(SB)
	MOVD	$522, R16
	B	runtime·callbackasm1(SB)
	MOVD	$523, R16
	B	runtime·callbackasm1(SB)
	MOVD	$524, R16
	B	runtime·callbackasm1(SB)
	MOVD	$525, R16
	B	runtime·callbackasm1(SB)
	MOVD	$526, R16
	B	runtime·callbackasm1(SB)
	MOVD	$527, R16
	B	runtime·callbackasm1(SB)
	MOVD	$528, R16
	B	runtime·callbackasm1(SB)
	MOVD	$529, R16
	B	runtime·callbackasm1(SB)
	MOVD	$530, R16
	B	runtime·callbackasm1(SB)
	MOVD	$531, R16
	B	runtime·callbackasm1(SB)
	MOVD	$532, R16
	B	runtime·callbackasm1(SB)
	MOVD	$533, R16
	B	runtime·callbackasm1(SB)
	MOVD	$534, R16
	B	runtime·callbackasm1(SB)
	MOVD	$535, R16
	B	runtime·callbackasm1(SB)
	MOVD	$536, R16
	B	runtime·callbackasm1(SB)
	MOVD	$537, R16
	B	runtime·callbackasm1(SB)
	MOVD	$538, R16
	B	runtime·callbackasm1(SB)
	MOVD	$539, R16
	B	runtime·callbackasm1(SB)
	MOVD	$540, R16
	B	runtime·callbackasm1(SB)
	MOVD	$541, R16
	B	runtime·callbackasm1(SB)
	MOVD	$542, R16
	B	runtime·callbackasm1(SB)
	MOVD	$543, R16
	B	runtime·callbackasm1(SB)
	MOVD	$544, R16
	B	runtime·callbackasm1(SB)
	MOVD	$545, R16
	B	runtime·callbackasm1(SB)
	MOVD	$546, R16
	B	runtime·callbackasm1(SB)
	MOVD	$547, R16
	B	runtime·callbackasm1(SB)
	MOVD	$548, R16
	B	runtime·callbackasm1(SB)
	MOVD	$549, R16
	B	runtime·callbackasm1(SB)
	MOVD	$550, R16
	B	runtime·callbackasm1(SB)
	MOVD	$551, R16
	B	runtime·callbackasm1(SB)
	MOVD	$552, R16
	B	runtime·callbackasm1(SB)
	MOVD	$553, R16
	B	runtime·callbackasm1(SB)
	MOVD	$554, R16
	B	runtime·callbackasm1(SB)
	MOVD	$555, R16
	B	runtime·callbackasm1(SB)
	MOVD	$556, R16
	B	runtime·callbackasm1(SB)
	MOVD	$557, R16
	B	runtime·callbackasm1(SB)
	MOVD	$558, R16
	B	runtime·callbackasm1(SB)
	MOVD	$559, R16
	B	runtime·callbackasm1(SB)
	MOVD	$560, R16
	B	runtime·callbackasm1(SB)
	MOVD	$561, R16
	B	runtime·callbackasm1(SB)
	MOVD	$562, R16
	B	runtime·callbackasm1(SB)
	MOVD	$563, R16
	B	runtime·callbackasm1(SB)
	MOVD	$564, R16
	B	runtime·callbackasm1(SB)
	MOVD	$565, R16
	B	runtime·callbackasm1(SB)
	MOVD	$566, R16
	B	runtime·callbackasm1(SB)
	MOVD	$567, R16
	B	runtime·callbackasm1(SB)
	MOVD	$568, R16
	B	runtime·callbackasm1(SB)
	MOVD	$569, R16
	B	runtime·callbackasm1(SB)
	MOVD	$570, R16
	B	runtime·callbackasm1(SB)
	MOVD	$571, R16
	B	runtime·callbackasm1(SB)
	MOVD	$572, R16
	B	runtime·callbackasm1(SB)
	MOVD	$573, R16
	B	runtime·callbackasm1(SB)
	MOVD	$574, R16
	B	runtime·callbackasm1(SB)
	MOVD	$575, R16
	B	runtime·callbackasm1(SB)
	MOVD	$576, R16
	B	runtime·callbackasm1(SB)
	MOVD	$577, R16
	B	runtime·callbackasm1(SB)
	MOVD	$578, R16
	B	runtime·callbackasm1(SB)
	MOVD	$579, R16
	B	runtime·callbackasm1(SB)
	MOVD	$580, R16
	B	runtime·callbackasm1(SB)
	MOVD	$581, R16
	B	runtime·callbackasm1(SB)
	MOVD	$582, R16
	B	runtime·callbackasm1(SB)
	MOVD	$583, R16
	B	runtime·callbackasm1(SB)
	MOVD	$584, R16
	B	runtime·callbackasm1(SB)
	MOVD	$585, R16
	B	runtime·callbackasm1(SB)
	MOVD	$586, R16
	B	runtime·callbackasm1(SB)
	MOVD	$587, R16
	B	runtime·callbackasm1(SB)
	MOVD	$588, R16
	B	runtime·callbackasm1(SB)
	MOVD	$589, R16
	B	runtime·callbackasm1(SB)
	MOVD	$590, R16
	B	runtime·callbackasm1(SB)
	MOVD	$591, R16
	B	runtime·callbackasm1(SB)
	MOVD	$592, R16
	B	runtime·callbackasm1(SB)
	MOVD	$593, R16
	B	runtime·callbackasm1(SB)
	MOVD	$594, R16
	B	runtime·callbackasm1(SB)
	MOVD	$595, R16
	B	runtime·callbackasm1(SB)
	MOVD	$596, R16
	B	runtime·callbackasm1(SB)
	MOVD	$597, R16
	B	runtime·callbackasm1(SB)
	MOVD	$598, R16
	B	runtime·callbackasm1(SB)
	MOVD	$599, R16
	B	runtime·callbackasm1(SB)
	MOVD	$600, R16
	B	runtime·callbackasm1(SB)
	MOVD	$601, R16
	B	runtime·callbackasm1(SB)
	MOVD	$602, R16
	B	runtime·callbackasm1(SB)
	MOVD	$603, R16
	B	runtime·callbackasm1(SB)
	MOVD	$604, R16
	B	runtime·callbackasm1(SB)
	MOVD	$605, R16
	B	runtime·callbackasm1(SB)
	MOVD	$606, R16
	B	runtime·callbackasm1(SB)
	MOVD	$607, R16
	B	runtime·callbackasm1(SB)
	MOVD	$608, R16
	B	runtime·callbackasm1(SB)
	MOVD	$609, R16
	B	runtime·callbackasm1(SB)
	MOVD	$610, R16
	B	runtime·callbackasm1(SB)
	MOVD	$611, R16
	B	runtime·callbackasm1(SB)
	MOVD	$612, R16
	B	runtime·callbackasm1(SB)
	MOVD	$613, R16
	B	runtime·callbackasm1(SB)
	MOVD	$614, R16
	B	runtime·callbackasm1(SB)
	MOVD	$615, R16
	B	runtime·callbackasm1(SB)
	MOVD	$616, R16
	B	runtime·callbackasm1(SB)
	MOVD	$617, R16
	B	runtime·callbackasm1(SB)
	MOVD	$618, R16
	B	runtime·callbackasm1(SB)
	MOVD	$619, R16
	B	runtime·callbackasm1(SB)
	MOVD	$620, R16
	B	runtime·callbackasm1(SB)
	MOVD	$621, R16
	B	runtime·callbackasm1(SB)
	MOVD	$622, R16
	B	runtime·callbackasm1(SB)
	MOVD	$623, R16
	B	runtime·callbackasm1(SB)
	MOVD	$624, R16
	B	runtime·callbackasm1(SB)
	MOVD	$625, R16
	B	runtime·callbackasm1(SB)
	MOVD	$626, R16
	B	runtime·callbackasm1(SB)
	MOVD	$627, R16
	B	runtime·callbackasm1(SB)
	MOVD	$628, R16
	B	runtime·callbackasm1(SB)
	MOVD	$629, R16
	B	runtime·callbackasm1(SB)
	MOVD	$630, R16
	B	runtime·callbackasm1(SB)
	MOVD	$631, R16
	B	runtime·callbackasm1(SB)
	MOVD	$632, R16
	B	runtime·callbackasm1(SB)
	MOVD	$633, R16
	B	runtime·callbackasm1(SB)
	MOVD	$634, R16
	B	runtime·callbackasm1(SB)
	MOVD	$635, R16
	B	runtime·callbackasm1(SB)
	MOVD	$636, R16
	B	runtime·callbackasm1(SB)
	MOVD	$637, R16
	B	runtime·callbackasm1(SB)
	MOVD	$638, R16
	B	runtime·callbackasm1(SB)
	MOVD	$639, R16
	B	runtime·callbackasm1(SB)
	MOVD	$640, R16
	B	runtime·callbackasm1(SB)
	MOVD	$641, R16
	B	runtime·callbackasm1(SB)
	MOVD	$642, R16
	B	runtime·callbackasm1(SB)
	MOVD	$643, R16
	B	runtime·callbackasm1(SB)
	MOVD	$644, R16
	B	runtime·callbackasm1(SB)
	MOVD	$645, R16
	B	runtime·callbackasm1(SB)
	MOVD	$646, R16
	B	runtime·callbackasm1(SB)
	MOVD	$647, R16
	B	runtime·callbackasm1(SB)
	MOVD	$648, R16
	B	runtime·callbackasm1(SB)
	MOVD	$649, R16
	B	runtime·callbackasm1(SB)
	MOVD	$650, R16
	B	runtime·callbackasm1(SB)
	MOVD	$651, R16
	B	runtime·callbackasm1(SB)
	MOVD	$652, R16
	B	runtime·callbackasm1(SB)
	MOVD	$653, R16
	B	runtime·callbackasm1(SB)
	MOVD	$654, R16
	B	runtime·callbackasm1(SB)
	MOVD	$655, R16
	B	runtime·callbackasm1(SB)
	MOVD	$656, R16
	B	runtime·callbackasm1(SB)
	MOVD	$657, R16
	B	runtime·callbackasm1(SB)
	MOVD	$658, R16
	B	runtime·callbackasm1(SB)
	MOVD	$659, R16
	B	runtime·callbackasm1(SB)
	MOVD	$660, R16
	B	runtime·callbackasm1(SB)
	MOVD	$661, R16
	B	runtime·callbackasm1(SB)
	MOVD	$662, R16
	B	runtime·callbackasm1(SB)
	MOVD	$663, R16
	B	runtime·callbackasm1(SB)
	MOVD	$664, R16
	B	runtime·callbackasm1(SB)
	MOVD	$665, R16
	B	runtime·callbackasm1(SB)
	MOVD	$666, R16
	B	runtime·callbackasm1(SB)
	MOVD	$667, R16
	B	runtime·callbackasm1(SB)
	MOVD	$668, R16
	B	runtime·callbackasm1(SB)
	MOVD	$669, R16
	B	runtime·callbackasm1(SB)
	MOVD	$670, R16
	B	runtime·callbackasm1(SB)
	MOVD	$671, R16
	B	runtime·callbackasm1(SB)
	MOVD	$672, R16
	B	runtime·callbackasm1(SB)
	MOVD	$673, R16
	B	runtime·callbackasm1(SB)
	MOVD	$674, R16
	B	runtime·callbackasm1(SB)
	MOVD	$675, R16
	B	runtime·callbackasm1(SB)
	MOVD	$676, R16
	B	runtime·callbackasm1(SB)
	MOVD	$677, R16
	B	runtime·callbackasm1(SB)
	MOVD	$678, R16
	B	runtime·callbackasm1(SB)
	MOVD	$679, R16
	B	runtime·callbackasm1(SB)
	MOVD	$680, R16
	B	runtime·callbackasm1(SB)
	MOVD	$681, R16
	B	runtime·callbackasm1(SB)
	MOVD	$682, R16
	B	runtime·callbackasm1(SB)
	MOVD	$683, R16
	B	runtime·callbackasm1(SB)
	MOVD	$684, R16
	B	runtime·callbackasm1(SB)
	MOVD	$685, R16
	B	runtime·callbackasm1(SB)
	MOVD	$686, R16
	B	runtime·callbackasm1(SB)
	MOVD	$687, R16
	B	runtime·callbackasm1(SB)
	MOVD	$688, R16
	B	runtime·callbackasm1(SB)
	MOVD	$689, R16
	B	runtime·callbackasm1(SB)
	MOVD	$690, R16
	B	runtime·callbackasm1(SB)
	MOVD	$691, R16
	B	runtime·callbackasm1(SB)
	MOVD	$692, R16
	B	runtime·callbackasm1(SB)
	MOVD	$693, R16
	B	runtime·callbackasm1(SB)
	MOVD	$694, R16
	B	runtime·callbackasm1(SB)
	MOVD	$695, R16
	B	runtime·callbackasm1(SB)
	MOVD	$696, R16
	B	runtime·callbackasm1(SB)
	MOVD	$697, R16
	B	runtime·callbackasm1(SB)
	MOVD	$698, R16
	B	runtime·callbackasm1(SB)
	MOVD	$699, R16
	B	runtime·callbackasm1(SB)
	MOVD	$700, R16
	B	runtime·callbackasm1(SB)
	MOVD	$701, R16
	B	runtime·callbackasm1(SB)
	MOVD	$702, R16
	B	runtime·callbackasm1(SB)
	MOVD	$703, R16
	B	runtime·callbackasm1(SB)
	MOVD	$704, R16
	B	runtime·callbackasm1(SB)
	MOVD	$705, R16
	B	runtime·callbackasm1(SB)
	MOVD	$706, R16
	B	runtime·callbackasm1(SB)
	MOVD	$707, R16
	B	runtime·callbackasm1(SB)
	MOVD	$708, R16
	B	runtime·callbackasm1(SB)
	MOVD	$709, R16
	B	runtime·callbackasm1(SB)
	MOVD	$710, R16
	B	runtime·callbackasm1(SB)
	MOVD	$711, R16
	B	runtime·callbackasm1(SB)
	MOVD	$712, R16
	B	runtime·callbackasm1(SB)
	MOVD	$713, R16
	B	runtime·callbackasm1(SB)
	MOVD	$714, R16
	B	runtime·callbackasm1(SB)
	MOVD	$715, R16
	B	runtime·callbackasm1(SB)
	MOVD	$716, R16
	B	runtime·callbackasm1(SB)
	MOVD	$717, R16
	B	runtime·callbackasm1(SB)
	MOVD	$718, R16
	B	runtime·callbackasm1(SB)
	MOVD	$719, R16
	B	runtime·callbackasm1(SB)
	MOVD	$720, R16
	B	runtime·callbackasm1(SB)
	MOVD	$721, R16
	B	runtime·callbackasm1(SB)
	MOVD	$722, R16
	B	runtime·callbackasm1(SB)
	MOVD	$723, R16
	B	runtime·callbackasm1(SB)
	MOVD	$724, R16
	B	runtime·callbackasm1(SB)
	MOVD	$725, R16
	B	runtime·callbackasm1(SB)
	MOVD	$726, R16
	B	runtime·callbackasm1(SB)
	MOVD	$727, R16
	B	runtime·callbackasm1(SB)
	MOVD	$728, R16
	B	runtime·callbackasm1(SB)
	MOVD	$729, R16
	B	runtime·callbackasm1(SB)
	MOVD	$730, R16
	B	runtime·callbackasm1(SB)
	MOVD	$731, R16
	B	runtime·callbackasm1(SB)
	MOVD	$732, R16
	B	runtime·callbackasm1(SB)
	MOVD	$733, R16
	B	runtime·callbackasm1(SB)
	MOVD	$734, R16
	B	runtime·callbackasm1(SB)
	MOVD	$735, R16
	B	runtime·callbackasm1(SB)
	MOVD	$736, R16
	B	runtime·callbackasm1(SB)
	MOVD	$737, R16
	B	runtime·callbackasm1(SB)
	MOVD	$738, R16
	B	runtime·callbackasm1(SB)
	MOVD	$739, R16
	B	runtime·callbackasm1(SB)
	MOVD	$740, R16
	B	runtime·callbackasm1(SB)
	MOVD	$741, R16
	B	runtime·callbackasm1(SB)
	MOVD	$742, R16
	B	runtime·callbackasm1(SB)
	MOVD	$743, R16
	B	runtime·callbackasm1(SB)
	MOVD	$744, R16
	B	runtime·callbackasm1(SB)
	MOVD	$745, R16
	B	runtime·callbackasm1(SB)
	MOVD	$746, R16
	B	runtime·callbackasm1(SB)
	MOVD	$747, R16
	B	runtime·callbackasm1(SB)
	MOVD	$748, R16
	B	runtime·callbackasm1(SB)
	MOVD	$749, R16
	B	runtime·callbackasm1(SB)
	MOVD	$750, R16
	B	runtime·callbackasm1(SB)
	MOVD	$751, R16
	B	runtime·callbackasm1(SB)
	MOVD	$752, R16
	B	runtime·callbackasm1(SB)
	MOVD	$753, R16
	B	runtime·callbackasm1(SB)
	MOVD	$754, R16
	B	runtime·callbackasm1(SB)
	MOVD	$755, R16
	B	runtime·callbackasm1(SB)
	MOVD	$756, R16
	B	runtime·callbackasm1(SB)
	MOVD	$757, R16
	B	runtime·callbackasm1(SB)
	MOVD	$758, R16
	B	runtime·callbackasm1(SB)
	MOVD	$759, R16
	B	runtime·callbackasm1(SB)
	MOVD	$760, R16
	B	runtime·callbackasm1(SB)
	MOVD	$761, R16
	B	runtime·callbackasm1(SB)
	MOVD	$762, R16
	B	runtime·callbackasm1(SB)
	MOVD	$763, R16
	B	runtime·callbackasm1(SB)
	MOVD	$764, R16
	B	runtime·callbackasm1(SB)
	MOVD	$765, R16
	B	runtime·callbackasm1(SB)
	MOVD	$766, R16
	B	runtime·callbackasm1(SB)
	MOVD	$767, R16
	B	runtime·callbackasm1(SB)
	MOVD	$768, R16
	B	runtime·callbackasm1(SB)
	MOVD	$769, R16
	B	runtime·callbackasm1(SB)
	MOVD	$770, R16
	B	runtime·callbackasm1(SB)
	MOVD	$771, R16
	B	runtime·callbackasm1(SB)
	MOVD	$772, R16
	B	runtime·callbackasm1(SB)
	MOVD	$773, R16
	B	runtime·callbackasm1(SB)
	MOVD	$774, R16
	B	runtime·callbackasm1(SB)
	MOVD	$775, R16
	B	runtime·callbackasm1(SB)
	MOVD	$776, R16
	B	runtime·callbackasm1(SB)
	MOVD	$777, R16
	B	runtime·callbackasm1(SB)
	MOVD	$778, R16
	B	runtime·callbackasm1(SB)
	MOVD	$779, R16
	B	runtime·callbackasm1(SB)
	MOVD	$780, R16
	B	runtime·callbackasm1(SB)
	MOVD	$781, R16
	B	runtime·callbackasm1(SB)
	MOVD	$782, R16
	B	runtime·callbackasm1(SB)
	MOVD	$783, R16
	B	runtime·callbackasm1(SB)
	MOVD	$784, R16
	B	runtime·callbackasm1(SB)
	MOVD	$785, R16
	B	runtime·callbackasm1(SB)
	MOVD	$786, R16
	B	runtime·callbackasm1(SB)
	MOVD	$787, R16
	B	runtime·callbackasm1(SB)
	MOVD	$788, R16
	B	runtime·callbackasm1(SB)
	MOVD	$789, R16
	B	runtime·callbackasm1(SB)
	MOVD	$790, R16
	B	runtime·callbackasm1(SB)
	MOVD	$791, R16
	B	runtime·callbackasm1(SB)
	MOVD	$792, R16
	B	runtime·callbackasm1(SB)
	MOVD	$793, R16
	B	runtime·callbackasm1(SB)
	MOVD	$794, R16
	B	runtime·callbackasm1(SB)
	MOVD	$795, R16
	B	runtime·callbackasm1(SB)
	MOVD	$796, R16
	B	runtime·callbackasm1(SB)
	MOVD	$797, R16
	B	runtime·callbackasm1(SB)
	MOVD	$798, R16
	B	runtime·callbackasm1(SB)
	MOVD	$799, R16
	B	runtime·callbackasm1(SB)
	MOVD	$800, R16
	B	runtime·callbackasm1(SB)
	MOVD	$801, R16
	B	runtime·callbackasm1(SB)
	MOVD	$802, R16
	B	runtime·callbackasm1(SB)
	MOVD	$803, R16
	B	runtime·callbackasm1(SB)
	MOVD	$804, R16
	B	runtime·callbackasm1(SB)
	MOVD	$805, R16
	B	runtime·callbackasm1(SB)
	MOVD	$806, R16
	B	runtime·callbackasm1(SB)
	MOVD	$807, R16
	B	runtime·callbackasm1(SB)
	MOVD	$808, R16
	B	runtime·callbackasm1(SB)
	MOVD	$809, R16
	B	runtime·callbackasm1(SB)
	MOVD	$810, R16
	B	runtime·callbackasm1(SB)
	MOVD	$811, R16
	B	runtime·callbackasm1(SB)
	MOVD	$812, R16
	B	runtime·callbackasm1(SB)
	MOVD	$813, R16
	B	runtime·callbackasm1(SB)
	MOVD	$814, R16
	B	runtime·callbackasm1(SB)
	MOVD	$815, R16
	B	runtime·callbackasm1(SB)
	MOVD	$816, R16
	B	runtime·callbackasm1(SB)
	MOVD	$817, R16
	B	runtime·callbackasm1(SB)
	MOVD	$818, R16
	B	runtime·callbackasm1(SB)
	MOVD	$819, R16
	B	runtime·callbackasm1(SB)
	MOVD	$820, R16
	B	runtime·callbackasm1(SB)
	MOVD	$821, R16
	B	runtime·callbackasm1(SB)
	MOVD	$822, R16
	B	runtime·callbackasm1(SB)
	MOVD	$823, R16
	B	runtime·callbackasm1(SB)
	MOVD	$824, R16
	B	runtime·callbackasm1(SB)
	MOVD	$825, R16
	B	runtime·callbackasm1(SB)
	MOVD	$826, R16
	B	runtime·callbackasm1(SB)
	MOVD	$827, R16
	B	runtime·callbackasm1(SB)
	MOVD	$828, R16
	B	runtime·callbackasm1(SB)
	MOVD	$829, R16
	B	runtime·callbackasm1(SB)
	MOVD	$830, R16
	B	runtime·callbackasm1(SB)
	MOVD	$831, R16
	B	runtime·callbackasm1(SB)
	MOVD	$832, R16
	B	runtime·callbackasm1(SB)
	MOVD	$833, R16
	B	runtime·callbackasm1(SB)
	MOVD	$834, R16
	B	runtime·callbackasm1(SB)
	MOVD	$835, R16
	B	runtime·callbackasm1(SB)
	MOVD	$836, R16
	B	runtime·callbackasm1(SB)
	MOVD	$837, R16
	B	runtime·callbackasm1(SB)
	MOVD	$838, R16
	B	runtime·callbackasm1(SB)
	MOVD	$839, R16
	B	runtime·callbackasm1(SB)
	MOVD	$840, R16
	B	runtime·callbackasm1(SB)
	MOVD	$841, R16
	B	runtime·callbackasm1(SB)
	MOVD	$842, R16
	B	runtime·callbackasm1(SB)
	MOVD	$843, R16
	B	runtime·callbackasm1(SB)
	MOVD	$844, R16
	B	runtime·callbackasm1(SB)
	MOVD	$845, R16
	B	runtime·callbackasm1(SB)
	MOVD	$846, R16
	B	runtime·callbackasm1(SB)
	MOVD	$847, R16
	B	runtime·callbackasm1(SB)
	MOVD	$848, R16
	B	runtime·callbackasm1(SB)
	MOVD	$849, R16
	B	runtime·callbackasm1(SB)
	MOVD	$850, R16
	B	runtime·callbackasm1(SB)
	MOVD	$851, R16
	B	runtime·callbackasm1(SB)
	MOVD	$852, R16
	B	runtime·callbackasm1(SB)
	MOVD	$853, R16
	B	runtime·callbackasm1(SB)
	MOVD	$854, R16
	B	runtime·callbackasm1(SB)
	MOVD	$855, R16
	B	runtime·callbackasm1(SB)
	MOVD	$856, R16
	B	runtime·callbackasm1(SB)
	MOVD	$857, R16
	B	runtime·callbackasm1(SB)
	MOVD	$858, R16
	B	runtime·callbackasm1(SB)
	MOVD	$859, R16
	B	runtime·callbackasm1(SB)
	MOVD	$860, R16
	B	runtime·callbackasm1(SB)
	MOVD	$861, R16
	B	runtime·callbackasm1(SB)
	MOVD	$862, R16
	B	runtime·callbackasm1(SB)
	MOVD	$863, R16
	B	runtime·callbackasm1(SB)
	MOVD	$864, R16
	B	runtime·callbackasm1(SB)
	MOVD	$865, R16
	B	runtime·callbackasm1(SB)
	MOVD	$866, R16
	B	runtime·callbackasm1(SB)
	MOVD	$867, R16
	B	runtime·callbackasm1(SB)
	MOVD	$868, R16
	B	runtime·callbackasm1(SB)
	MOVD	$869, R16
	B	runtime·callbackasm1(SB)
	MOVD	$870, R16
	B	runtime·callbackasm1(SB)
	MOVD	$871, R16
	B	runtime·callbackasm1(SB)
	MOVD	$872, R16
	B	runtime·callbackasm1(SB)
	MOVD	$873, R16
	B	runtime·callbackasm1(SB)
	MOVD	$874, R16
	B	runtime·callbackasm1(SB)
	MOVD	$875, R16
	B	runtime·callbackasm1(SB)
	MOVD	$876, R16
	B	runtime·callbackasm1(SB)
	MOVD	$877, R16
	B	runtime·callbackasm1(SB)
	MOVD	$878, R16
	B	runtime·callbackasm1(SB)
	MOVD	$879, R16
	B	runtime·callbackasm1(SB)
	MOVD	$880, R16
	B	runtime·callbackasm1(SB)
	MOVD	$881, R16
	B	runtime·callbackasm1(SB)
	MOVD	$882, R16
	B	runtime·callbackasm1(SB)
	MOVD	$883, R16
	B	runtime·callbackasm1(SB)
	MOVD	$884, R16
	B	runtime·callbackasm1(SB)
	MOVD	$885, R16
	B	runtime·callbackasm1(SB)
	MOVD	$886, R16
	B	runtime·callbackasm1(SB)
	MOVD	$887, R16
	B	runtime·callbackasm1(SB)
	MOVD	$888, R16
	B	runtime·callbackasm1(SB)
	MOVD	$889, R16
	B	runtime·callbackasm1(SB)
	MOVD	$890, R16
	B	runtime·callbackasm1(SB)
	MOVD	$891, R16
	B	runtime·callbackasm1(SB)
	MOVD	$892, R16
	B	runtime·callbackasm1(SB)
	MOVD	$893, R16
	B	runtime·callbackasm1(SB)
	MOVD	$894, R16
	B	runtime·callbackasm1(SB)
	MOVD	$895, R16
	B	runtime·callbackasm1(SB)
	MOVD	$896, R16
	B	runtime·callbackasm1(SB)
	MOVD	$897, R16
	B	runtime·callbackasm1(SB)
	MOVD	$898, R16
	B	runtime·callbackasm1(SB)
	MOVD	$899, R16
	B	runtime·callbackasm1(SB)
	MOVD	$900, R16
	B	runtime·callbackasm1(SB)
	MOVD	$901, R16
	B	runtime·callbackasm1(SB)
	MOVD	$902, R16
	B	runtime·callbackasm1(SB)
	MOVD	$903, R16
	B	runtime·callbackasm1(SB)
	MOVD	$904, R16
	B	runtime·callbackasm1(SB)
	MOVD	$905, R16
	B	runtime·callbackasm1(SB)
	MOVD	$906, R16
	B	runtime·callbackasm1(SB)
	MOVD	$907, R16
	B	runtime·callbackasm1(SB)
	MOVD	$908, R16
	B	runtime·callbackasm1(SB)
	MOVD	$909, R16
	B	runtime·callbackasm1(SB)
	MOVD	$910, R16
	B	runtime·callbackasm1(SB)
	MOVD	$911, R16
	B	runtime·callbackasm1(SB)
	MOVD	$912, R16
	B	runtime·callbackasm1(SB)
	MOVD	$913, R16
	B	runtime·callbackasm1(SB)
	MOVD	$914, R16
	B	runtime·callbackasm1(SB)
	MOVD	$915, R16
	B	runtime·callbackasm1(SB)
	MOVD	$916, R16
	B	runtime·callbackasm1(SB)
	MOVD	$917, R16
	B	runtime·callbackasm1(SB)
	MOVD	$918, R16
	B	runtime·callbackasm1(SB)
	MOVD	$919, R16
	B	runtime·callbackasm1(SB)
	MOVD	$920, R16
	B	runtime·callbackasm1(SB)
	MOVD	$921, R16
	B	runtime·callbackasm1(SB)
	MOVD	$922, R16
	B	runtime·callbackasm1(SB)
	MOVD	$923, R16
	B	runtime·callbackasm1(SB)
	MOVD	$924, R16
	B	runtime·callbackasm1(SB)
	MOVD	$925, R16
	B	runtime·callbackasm1(SB)
	MOVD	$926, R16
	B	runtime·callbackasm1(SB)
	MOVD	$927, R16
	B	runtime·callbackasm1(SB)
	MOVD	$928, R16
	B	runtime·callbackasm1(SB)
	MOVD	$929, R16
	B	runtime·callbackasm1(SB)
	MOVD	$930, R16
	B	runtime·callbackasm1(SB)
	MOVD	$931, R16
	B	runtime·callbackasm1(SB)
	MOVD	$932, R16
	B	runtime·callbackasm1(SB)
	MOVD	$933, R16
	B	runtime·callbackasm1(SB)
	MOVD	$934, R16
	B	runtime·callbackasm1(SB)
	MOVD	$935, R16
	B	runtime·callbackasm1(SB)
	MOVD	$936, R16
	B	runtime·callbackasm1(SB)
	MOVD	$937, R16
	B	runtime·callbackasm1(SB)
	MOVD	$938, R16
	B	runtime·callbackasm1(SB)
	MOVD	$939, R16
	B	runtime·callbackasm1(SB)
	MOVD	$940, R16
	B	runtime·callbackasm1(SB)
	MOVD	$941, R16
	B	runtime·callbackasm1(SB)
	MOVD	$942, R16
	B	runtime·callbackasm1(SB)
	MOVD	$943, R16
	B	runtime·callbackasm1(SB)
	MOVD	$944, R16
	B	runtime·callbackasm1(SB)
	MOVD	$945, R16
	B	runtime·callbackasm1(SB)
	MOVD	$946, R16
	B	runtime·callbackasm1(SB)
	MOVD	$947, R16
	B	runtime·callbackasm1(SB)
	MOVD	$948, R16
	B	runtime·callbackasm1(SB)
	MOVD	$949, R16
	B	runtime·callbackasm1(SB)
	MOVD	$950, R16
	B	runtime·callbackasm1(SB)
	MOVD	$951, R16
	B	runtime·callbackasm1(SB)
	MOVD	$952, R16
	B	runtime·callbackasm1(SB)
	MOVD	$953, R16
	B	runtime·callbackasm1(SB)
	MOVD	$954, R16
	B	runtime·callbackasm1(SB)
	MOVD	$955, R16
	B	runtime·callbackasm1(SB)
	MOVD	$956, R16
	B	runtime·callbackasm1(SB)
	MOVD	$957, R16
	B	runtime·callbackasm1(SB)
	MOVD	$958, R16
	B	runtime·callbackasm1(SB)
	MOVD	$959, R16
	B	runtime·callbackasm1(SB)
	MOVD	$960, R16
	B	runtime·callbackasm1(SB)
	MOVD	$961, R16
	B	runtime·callbackasm1(SB)
	MOVD	$962, R16
	B	runtime·callbackasm1(SB)
	MOVD	$963, R16
	B	runtime·callbackasm1(SB)
	MOVD	$964, R16
	B	runtime·callbackasm1(SB)
	MOVD	$965, R16
	B	runtime·callbackasm1(SB)
	MOVD	$966, R16
	B	runtime·callbackasm1(SB)
	MOVD	$967, R16
	B	runtime·callbackasm1(SB)
	MOVD	$968, R16
	B	runtime·callbackasm1(SB)
	MOVD	$969, R16
	B	runtime·callbackasm1(SB)
	MOVD	$970, R16
	B	runtime·callbackasm1(SB)
	MOVD	$971, R16
	B	runtime·callbackasm1(SB)
	MOVD	$972, R16
	B	runtime·callbackasm1(SB)
	MOVD	$973, R16
	B	runtime·callbackasm1(SB)
	MOVD	$974, R16
	B	runtime·callbackasm1(SB)
	MOVD	$975, R16
	B	runtime·callbackasm1(SB)
	MOVD	$976, R16
	B	runtime·callbackasm1(SB)
	MOVD	$977, R16
	B	runtime·callbackasm1(SB)
	MOVD	$978, R16
	B	runtime·callbackasm1(SB)
	MOVD	$979, R16
	B	runtime·callbackasm1(SB)
	MOVD	$980, R16
	B	runtime·callbackasm1(SB)
	MOVD	$981, R16
	B	runtime·callbackasm1(SB)
	MOVD	$982, R16
	B	runtime·callbackasm1(SB)
	MOVD	$983, R16
	B	runtime·callbackasm1(SB)
	MOVD	$984, R16
	B	runtime·callbackasm1(SB)
	MOVD	$985, R16
	B	runtime·callbackasm1(SB)
	MOVD	$986, R16
	B	runtime·callbackasm1(SB)
	MOVD	$987, R16
	B	runtime·callbackasm1(SB)
	MOVD	$988, R16
	B	runtime·callbackasm1(SB)
	MOVD	$989, R16
	B	runtime·callbackasm1(SB)
	MOVD	$990, R16
	B	runtime·callbackasm1(SB)
	MOVD	$991, R16
	B	runtime·callbackasm1(SB)
	MOVD	$992, R16
	B	runtime·callbackasm1(SB)
	MOVD	$993, R16
	B	runtime·callbackasm1(SB)
	MOVD	$994, R16
	B	runtime·callbackasm1(SB)
	MOVD	$995, R16
	B	runtime·callbackasm1(SB)
	MOVD	$996, R16
	B	runtime·callbackasm1(SB)
	MOVD	$997, R16
	B	runtime·callbackasm1(SB)
	MOVD	$998, R16
	B	runtime·callbackasm1(SB)
	MOVD	$999, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1000, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1001, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1002, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1003, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1004, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1005, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1006, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1007, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1008, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1009, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1010, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1011, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1012, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1013, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1014, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1015, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1016, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1017, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1018, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1019, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1020, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1021, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1022, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1023, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1024, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1025, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1026, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1027, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1028, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1029, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1030, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1031, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1032, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1033, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1034, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1035, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1036, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1037, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1038, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1039, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1040, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1041, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1042, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1043, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1044, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1045, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1046, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1047, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1048, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1049, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1050, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1051, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1052, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1053, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1054, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1055, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1056, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1057, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1058, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1059, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1060, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1061, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1062, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1063, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1064, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1065, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1066, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1067, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1068, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1069, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1070, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1071, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1072, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1073, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1074, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1075, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1076, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1077, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1078, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1079, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1080, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1081, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1082, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1083, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1084, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1085, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1086, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1087, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1088, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1089, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1090, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1091, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1092, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1093, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1094, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1095, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1096, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1097, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1098, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1099, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1100, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1101, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1102, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1103, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1104, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1105, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1106, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1107, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1108, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1109, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1110, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1111, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1112, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1113, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1114, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1115, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1116, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1117, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1118, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1119, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1120, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1121, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1122, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1123, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1124, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1125, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1126, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1127, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1128, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1129, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1130, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1131, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1132, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1133, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1134, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1135, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1136, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1137, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1138, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1139, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1140, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1141, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1142, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1143, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1144, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1145, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1146, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1147, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1148, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1149, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1150, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1151, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1152, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1153, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1154, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1155, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1156, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1157, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1158, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1159, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1160, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1161, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1162, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1163, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1164, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1165, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1166, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1167, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1168, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1169, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1170, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1171, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1172, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1173, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1174, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1175, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1176, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1177, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1178, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1179, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1180, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1181, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1182, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1183, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1184, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1185, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1186, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1187, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1188, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1189, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1190, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1191, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1192, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1193, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1194, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1195, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1196, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1197, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1198, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1199, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1200, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1201, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1202, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1203, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1204, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1205, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1206, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1207, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1208, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1209, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1210, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1211, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1212, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1213, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1214, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1215, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1216, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1217, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1218, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1219, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1220, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1221, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1222, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1223, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1224, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1225, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1226, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1227, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1228, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1229, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1230, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1231, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1232, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1233, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1234, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1235, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1236, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1237, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1238, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1239, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1240, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1241, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1242, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1243, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1244, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1245, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1246, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1247, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1248, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1249, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1250, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1251, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1252, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1253, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1254, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1255, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1256, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1257, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1258, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1259, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1260, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1261, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1262, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1263, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1264, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1265, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1266, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1267, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1268, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1269, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1270, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1271, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1272, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1273, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1274, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1275, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1276, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1277, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1278, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1279, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1280, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1281, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1282, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1283, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1284, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1285, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1286, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1287, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1288, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1289, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1290, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1291, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1292, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1293, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1294, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1295, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1296, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1297, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1298, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1299, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1300, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1301, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1302, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1303, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1304, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1305, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1306, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1307, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1308, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1309, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1310, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1311, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1312, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1313, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1314, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1315, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1316, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1317, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1318, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1319, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1320, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1321, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1322, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1323, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1324, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1325, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1326, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1327, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1328, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1329, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1330, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1331, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1332, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1333, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1334, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1335, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1336, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1337, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1338, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1339, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1340, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1341, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1342, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1343, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1344, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1345, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1346, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1347, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1348, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1349, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1350, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1351, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1352, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1353, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1354, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1355, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1356, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1357, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1358, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1359, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1360, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1361, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1362, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1363, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1364, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1365, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1366, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1367, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1368, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1369, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1370, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1371, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1372, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1373, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1374, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1375, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1376, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1377, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1378, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1379, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1380, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1381, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1382, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1383, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1384, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1385, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1386, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1387, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1388, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1389, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1390, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1391, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1392, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1393, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1394, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1395, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1396, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1397, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1398, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1399, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1400, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1401, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1402, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1403, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1404, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1405, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1406, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1407, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1408, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1409, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1410, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1411, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1412, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1413, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1414, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1415, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1416, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1417, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1418, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1419, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1420, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1421, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1422, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1423, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1424, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1425, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1426, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1427, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1428, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1429, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1430, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1431, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1432, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1433, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1434, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1435, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1436, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1437, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1438, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1439, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1440, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1441, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1442, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1443, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1444, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1445, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1446, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1447, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1448, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1449, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1450, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1451, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1452, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1453, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1454, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1455, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1456, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1457, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1458, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1459, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1460, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1461, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1462, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1463, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1464, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1465, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1466, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1467, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1468, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1469, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1470, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1471, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1472, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1473, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1474, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1475, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1476, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1477, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1478, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1479, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1480, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1481, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1482, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1483, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1484, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1485, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1486, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1487, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1488, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1489, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1490, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1491, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1492, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1493, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1494, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1495, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1496, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1497, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1498, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1499, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1500, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1501, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1502, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1503, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1504, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1505, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1506, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1507, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1508, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1509, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1510, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1511, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1512, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1513, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1514, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1515, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1516, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1517, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1518, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1519, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1520, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1521, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1522, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1523, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1524, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1525, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1526, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1527, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1528, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1529, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1530, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1531, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1532, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1533, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1534, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1535, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1536, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1537, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1538, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1539, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1540, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1541, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1542, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1543, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1544, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1545, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1546, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1547, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1548, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1549, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1550, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1551, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1552, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1553, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1554, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1555, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1556, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1557, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1558, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1559, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1560, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1561, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1562, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1563, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1564, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1565, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1566, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1567, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1568, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1569, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1570, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1571, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1572, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1573, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1574, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1575, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1576, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1577, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1578, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1579, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1580, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1581, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1582, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1583, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1584, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1585, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1586, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1587, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1588, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1589, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1590, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1591, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1592, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1593, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1594, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1595, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1596, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1597, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1598, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1599, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1600, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1601, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1602, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1603, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1604, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1605, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1606, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1607, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1608, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1609, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1610, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1611, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1612, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1613, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1614, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1615, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1616, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1617, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1618, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1619, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1620, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1621, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1622, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1623, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1624, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1625, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1626, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1627, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1628, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1629, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1630, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1631, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1632, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1633, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1634, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1635, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1636, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1637, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1638, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1639, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1640, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1641, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1642, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1643, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1644, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1645, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1646, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1647, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1648, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1649, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1650, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1651, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1652, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1653, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1654, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1655, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1656, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1657, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1658, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1659, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1660, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1661, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1662, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1663, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1664, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1665, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1666, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1667, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1668, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1669, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1670, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1671, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1672, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1673, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1674, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1675, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1676, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1677, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1678, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1679, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1680, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1681, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1682, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1683, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1684, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1685, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1686, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1687, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1688, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1689, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1690, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1691, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1692, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1693, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1694, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1695, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1696, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1697, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1698, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1699, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1700, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1701, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1702, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1703, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1704, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1705, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1706, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1707, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1708, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1709, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1710, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1711, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1712, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1713, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1714, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1715, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1716, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1717, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1718, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1719, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1720, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1721, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1722, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1723, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1724, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1725, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1726, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1727, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1728, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1729, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1730, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1731, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1732, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1733, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1734, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1735, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1736, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1737, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1738, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1739, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1740, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1741, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1742, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1743, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1744, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1745, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1746, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1747, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1748, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1749, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1750, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1751, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1752, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1753, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1754, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1755, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1756, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1757, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1758, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1759, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1760, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1761, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1762, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1763, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1764, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1765, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1766, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1767, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1768, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1769, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1770, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1771, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1772, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1773, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1774, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1775, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1776, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1777, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1778, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1779, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1780, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1781, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1782, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1783, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1784, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1785, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1786, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1787, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1788, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1789, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1790, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1791, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1792, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1793, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1794, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1795, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1796, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1797, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1798, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1799, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1800, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1801, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1802, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1803, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1804, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1805, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1806, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1807, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1808, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1809, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1810, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1811, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1812, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1813, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1814, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1815, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1816, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1817, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1818, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1819, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1820, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1821, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1822, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1823, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1824, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1825, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1826, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1827, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1828, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1829, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1830, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1831, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1832, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1833, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1834, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1835, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1836, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1837, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1838, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1839, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1840, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1841, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1842, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1843, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1844, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1845, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1846, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1847, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1848, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1849, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1850, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1851, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1852, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1853, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1854, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1855, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1856, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1857, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1858, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1859, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1860, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1861, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1862, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1863, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1864, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1865, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1866, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1867, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1868, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1869, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1870, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1871, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1872, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1873, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1874, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1875, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1876, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1877, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1878, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1879, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1880, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1881, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1882, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1883, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1884, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1885, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1886, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1887, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1888, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1889, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1890, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1891, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1892, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1893, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1894, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1895, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1896, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1897, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1898, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1899, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1900, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1901, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1902, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1903, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1904, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1905, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1906, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1907, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1908, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1909, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1910, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1911, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1912, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1913, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1914, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1915, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1916, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1917, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1918, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1919, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1920, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1921, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1922, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1923, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1924, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1925, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1926, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1927, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1928, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1929, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1930, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1931, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1932, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1933, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1934, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1935, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1936, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1937, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1938, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1939, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1940, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1941, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1942, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1943, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1944, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1945, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1946, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1947, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1948, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1949, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1950, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1951, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1952, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1953, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1954, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1955, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1956, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1957, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1958, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1959, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1960, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1961, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1962, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1963, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1964, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1965, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1966, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1967, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1968, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1969, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1970, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1971, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1972, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1973, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1974, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1975, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1976, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1977, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1978, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1979, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1980, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1981, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1982, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1983, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1984, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1985, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1986, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1987, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1988, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1989, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1990, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1991, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1992, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1993, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1994, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1995, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1996, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1997, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1998, R16
	B	runtime·callbackasm1(SB)
	MOVD	$1999, R16
	B	runtime·callbackasm1(SB)
